theme: jekyll-theme-minimal
title: Manu Singh
description: PhD Candidate
logo: https://github.com/manusingh3/manusingh3.github.io/blob/58959b5c98e4b4920a0c8e0128fbecf42df67190/images/manu_white_background.png
show_downloads: false
