theme: jekyll-theme-minimal
title: Manu Singh
description: PhD Candidate
logo: https://media.licdn.com/dms/image/C4E03AQExoe8I4kVAug/profile-displayphoto-shrink_800_800/0/1558445107285?e=1701302400&v=beta&t=V45Ouofkdg2v91Lx0sn1VoYpvqHDcaf023ycIYqZPN4
show_downloads: false
