name: Build and Deploy Jekyll

on:
  push:
    branches:
      - master  # Trigger on changes to the master branch (use 'main' if your default branch is 'main')
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Ensure the Ruby version matches your Jekyll requirements

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          bundle install

      # Step 4: Build the site
      - name: Build site
        run: bundle exec jekyll build

      # Optional: Deploy to GitHub Pages (requires GitHub Pages setup)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
